name: SPEEDUP OFFLINE PACKAGES
on:
  workflow_call:

jobs:
  speedup_offline_packages:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        name: [files-amd64, images-amd64, files-arm64, images-arm64, os-pkgs-centos7, os-pkgs-kylinv10, os-pkgs-redhat8, os-pkgs-redhat7]

    steps:
      - name: wget_files
        run: |
          BASE_URL="https://files.m.daocloud.io/github.com/kubean-io/kubean/releases/download"
          echo "Start speed up ${{ matrix.name }}"
          echo "${{ inputs.S_TAG }} "
          file_name="${BASE_URL}/${{ inputs.S_TAG }}/${{ matrix.name }}-${{ inputs.S_TAG }}.tar.gz"
          echo "${file_name}"
          wget -q -c -T 1m ${BASE_URL}/${GITHUB_REF_NAME}/${{ matrix.name }}-${GITHUB_REF_NAME}.tar.gz